services:
  db_1:
    container_name: mariadb-fracmentacion-1
    image: mariadb:12
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: 123456
      MARIADB_DATABASE: customers
      MARIADB_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - ./mariadb_1:/var/lib/mysql:Z
    networks:
      internal_network:
      lab_net_db:
        ipv4_address: 192.168.20.130

  db_2:
    container_name: mariadb-fracmentacion-2
    image: mariadb:12
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: 123456
      MARIADB_DATABASE: customers
      MARIADB_ROOT_PASSWORD: 123456
    ports:
      - 3307:3306
    volumes:
      - ./mariadb_2:/var/lib/mysql:Z
    networks:
      internal_network:
      lab_net_db:
        ipv4_address: 192.168.20.131

networks:
  internal_network:
    driver: bridge

  lab_net_db:
    driver: macvlan
    driver_opts:
      parent: enp3s0f0
    ipam:
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.1

volumes:
  mariadb_1:
  mariadb_2:

